export type CharacterMap = [number, string, string]

export const Characters: Array<CharacterMap> = [
  [1, "mario", "Mario"],
  [2, "donkey", "Donkey Kong"],
  [3, "link", "Link"],
  [4, "samus", "Samus"],
  [5, "samusd", "Dark Samus"],
  [6, "yoshi", "Yoshi"],
  [7, "kirby", "Kirby"],
  [8, "fox", "Fox"],
  [9, "pikachu", "Pikachu"],
  [10, "luigi", "Luigi"],
  [11, "ness", "Ness"],
  [12, "captain", "Captain Falcon"],
  [13, "purin", "Jigglypuff"],
  [14, "peach", "Peach"],
  [15, "daisy", "Daisy"],
  [16, "koopa", "Bowser"],
  [17, "ice_climber", "Ice Climbers"],
  [18, "sheik", "Shiek"],
  [19, "zelda", "Zelda"],
  [20, "mariod", "Dr. Mario"],
  [21, "pichu", "Pichu"],
  [22, "falco", "Falco"],
  [23, "marth", "Marth"],
  [24, "lucina", "Lucina"],
  [25, "younglink", "Young Link"],
  [26, "ganon", "Ganondorf"],
  [27, "mewtwo", "Mewtwo"],
  [28, "roy", "Roy"],
  [29, "chrom", "Chrom"],
  [30, "gamewatch", "Mr. Game & Watch"],
  [31, "metaknight", "Meta Knight"],
  [32, "pit", "Pit"],
  [33, "pitb", "Dark Pit"],
  [34, "szerosuit", "Zero Suit Samus"],
  [35, "wario", "Wario"],
  [36, "snake", "Snake"],
  [37, "ike", "Ike"],
  [38, "ptrainer", "Pokemon Trainer"],
  [39, "pzenigame", "Squirtle"],
  [40, "pfushigisou", "Ivysaur"],
  [41, "plizardon", "Charizard"],
  [42, "diddy", "Diddy Kong"],
  [43, "lucas", "Lucas"],
  [44, "sonic", "Sonic"],
  [45, "dedede", "King Dedede"],
  [46, "pikmin", "Pikmin & Olimar"],
  [47, "lucario", "Lucario"],
  [48, "robot", "R.O.B."],
  [49, "toonlink", "Toon Link"],
  [50, "wolf", "Wolf"],
  [51, "murabito", "Villager"],
  [52, "rockman", "Megaman"],
  [53, "wiifit", "Wii Fit Trainer"],
  [54, "rosetta", "Roselina"],
  [55, "littlemac", "Little Mac"],
  [56, "gekkouga", "Greninja"],
  [57, "palutena", "Palutena"],
  [58, "pacman", "Pacman"],
  [59, "reflet", "Robin"],
  [60, "shulk", "Shulk"],
  [61, "koopajr", "Bowser Jr."],
  [62, "duckhunt", "Duck Hunt"],
  [63, "ryu", "Ryu"],
  [64, "ken", "Ken"],
  [65, "cloud", "Cloud"],
  [66, "kamui", "Corrin"],
  [67, "bayonetta", "Bayonetta"],
  [68, "richter", "Richter"],
  [69, "inkling", "Inkling"],
  [70, "ridley", "Ridley"],
  [71, "krool", "King K. Rool"],
  [72, "simon", "Simon"],
  [73, "shizue", "Isabelle"],
  [74, "gaogaen", "Incineroar"],
  [75, "miiall", "Mii"],
  [76, "miifighter", "Mii Fighter"],
  [77, "miiswordsman", "Mii Swordfighter"],
  [78, "miigunner", "Mii Gunner"],
  [105, "packun", "Piranha Plant"],
  [106, "jack", "Jocker"],
  [107, "brave", "Hero"],
  [108, "buddy", "Banjo & Kazooie"],
  [109, "dolly", "Terry"],
  [110, "master", "Byleth"],
  [111, "tantan", "Min Min"],
  [112, "pickel", "Steve"],
  [113, "edge", "Sepiroth"],
  [114, "element", "Pyra/Mythra"],
  // [115, "eflame_first", "Pyra/Mythra"],
  // [116, "elight_first", "Mythra/Pyra"],
  // [117, "eflame_only", "Pyra"],
  // [118, "elight_only", "Mythra"],
  [119, "demon", "Kazuya"],
  [120, "trail", "Sora"],
  // [1, "nana", "Nana"],
  // [1, "popo", "Popo"],
]